export const SEARCH_PROJECTS_PENDING = 'SEARCH_PROJECTS_PENDING'
export const SEARCH_PROJECTS_ERROR = 'SEARCH_PROJECTS_ERROR'
export const SEARCH_PROJECTS_SUCCESS = 'SEARCH_PROJECTS_SUCCESS'

export const FETCH_PROJECTS_PENDING = 'FETCH_PROJECTS_PENDING'
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'

export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD'